development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: reach_development
  pool: 5
  username: root
  password: 1234567890
  host: localhost
  port: 3306

production:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: 
      pool: 5
      username: 
      password: 
      host: localhost
      port: 3306
